# pylint: disable=line-too-long
"""
motivators.py

This module contains a collection of motivational messages, interesting facts,
and quotes for use in a work timer application.

DISCLAIMER: This entire module, including the code, comments, and the content itself,
was generated completely by a Large Language Model (LLM). This LLM is
powered by a significant investment of resources (we're talking billions, folks,
for reasons that are sometimes as clear as mud!). While the LLM did a great job,
it doesn't own the quotes it pulled. The original authors (or their estates)
likely hold the copyright. In case of messages the copyright belongs to whoever came up with
the message (or it may be in public domain).

What does this mean for you? Well, if you're planning to reuse this code (especially
in a commercial setting), you might want to double-check the copyright status of each
item individually. The developers of this work timer aren't lawyers, and neither
is the LLM (though it probably could pass the bar exam... scary thought, right?).

In short: Use this content responsibly, attribute appropriately where possible,
and if you're making big bucks off this code, maybe consult a real-life human lawyer.
They're expensive, but usually less so than lawsuits.

And now, without further ado, a collection of wisdom brought to you by cutting-edge
AI and a whole lot of electricity... Enjoy!
"""

MOTIVATORS = [
    # Motivational/Inspirational:
    "Time to shine! What will you create today?",
    "Small steps lead to big things. Let's get moving!",
    "The best way to predict the future is to create it. Get to work!",
    "Focus on progress, not perfection. Start now.",
    "You are capable of amazing things. Prove it to yourself today.",
    "A journey of a thousand miles begins with a single step. Take that step now.",
    "Don't wait for opportunity. Create it.",
    "The only way to do great work is to love what you do. Find your passion.",
    "Your only limit is the one you set yourself. Break through it.",
    "What's one thing you can do *right now* to move closer to your goals?",
    "Make today your masterpiece.",
    "Believe you can and you're halfway there.",
    "Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "The secret of getting ahead is getting started.",
    "You don't have to be great to start, but you have to start to be great.",
    "Start where you are. Use what you have. Do what you can.",
    "The future depends on what you do today.",
    "Every day is a new opportunity to change your life.",
    "Be the change that you wish to see in the world.",
    "The only person you are destined to become is the person you decide to be.",
    "Go confidently in the direction of your dreams! Live the life you've imagined.",
    "What lies behind you and what lies before you are tiny matters compared to what lies within you.",
    "It does not matter how slowly you go as long as you do not stop.",
    "You are never too old to set another goal or to dream a new dream.",
    "The mind is everything. What you think you become.",
    "Everything you've ever wanted is on the other side of fear.",
    "Success usually comes to those who are too busy to be looking for it.",
    "If you can dream it, you can do it.",
    "Don't watch the clock; do what it does. Keep going.",
    "Action is the foundational key to all success.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "There are no shortcuts to any place worth going.",
    "Push yourself, because no one else is going to do it for you.",
    "The difference between ordinary and extraordinary is that little extra.",
    "You are stronger than you think.",
    "Difficult roads often lead to beautiful destinations.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "It always seems impossible until it's done.",
    "You don't have to see the whole staircase, just take the first step.",

    # Funny/Whimsical:
    "Your future self will thank you for working now. (Probably.)",
    "Procrastination is the art of keeping up with yesterday. Let's not do that.",
    "Warning: Excessive leisure may cause you to become a couch potato. Avoid this fate!",
    "Remember, even a broken clock is right twice a day. Let's be right more often.",
    "I believe in you! (Also, I'm a computer program, so my opinion is worth what you paid for it.)",
    "Beep boop! It is time for productive human activities!",
    "If at first you don't succeed... you're running about average. Try again!",
    "The early bird gets the worm. But the second mouse gets the cheese.",
    "Time is a great teacher, but unfortunately it kills all its pupils.",
    "Don't let yesterday take up too much of today.",
    "I'm not saying you should work... but the internet isn't going to browse itself.",
    "I'm not lazy, I'm on energy-saving mode.",
    "Why be a procrastinator when you can be a pro-cricket player... on your phone? Wait, no, work!",
    "I need to be more productive... said no cat ever. Be productive. Don't be a cat.",
    "My bed is a magical place where I suddenly remember everything I forgot to do.",
    "Doing nothing is hard, you never know when you're done.",
    "The road to success is dotted with many tempting parking spaces.",
    "Sure, I do marathons. On Netflix.",
    "Life is short. Smile while you still have teeth. And work while you still have a job!",
    "I'm not arguing, I'm just explaining why I'm right and you should be working.",
    "Work: the thing you do so you can afford to do other things. Like sleep. Do both!",
    "Adulting is soup and I am a fork. Help me be a spoon and get stuff done!",
    "I followed my heart and it led me to the fridge. Let's not do that. Let's work.",
    "Procrastinate now, don't put it off until later.",
    "My brain has too many tabs open. Time to close some with work.",
    "I put the 'pro' in procrastination. Let's change that to 'productive'!",
    "To be or not to be... productive. Let's choose 'to be'!",
    "An apple a day keeps the doctor away. But a productive day keeps the boss happy!",
    "Exercise? I thought you said extra fries! Let's exercise our work ethic instead.",
    "I'm not sure how many problems I have because math is one of them. Let's solve the work problem!",

    # Interesting Factoids:
    "Did you know the average person walks the equivalent of five times around the world in their lifetime? Time to get stepping... or working!",
    "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible! Get busy making something that lasts.",
    "The shortest war in history was between Britain and Zanzibar in 1896. Zanzibar surrendered after 38 minutes. Let's aim for a slightly longer work session.",
    "A group of owls is called a parliament. A group of programmers is called... well, it depends on the day.",
    "The word 'nerd' was first coined by Dr. Seuss in his book 'If I Ran the Zoo' (1950).",
    "Did you know? The population of the Earth is over 8 billion people. You're one of them. Get back to work.",
    "Octopuses have three hearts. How many productive hours will you have today?",
    "The longest time between two twins being born is 87 days. Let's see if you can work for longer than that.",
    "Cleopatra lived closer in time to the invention of the iPhone than to the building of the Great Pyramid. Time flies! Get to work!",
    "There are more possible iterations of a game of chess than there are atoms in the known universe. Let's make some moves!",
    "It takes a photon up to 40,000 years to travel from the core of the Sun to its surface, but only 8 minutes to reach Earth from there. Be like the latter part of the photon's journey!",
    "Bananas are curved because they grow towards the sun. Grow towards your goals!",
    "The unicorn is the national animal of Scotland. What's your spirit animal? Channel it and work!",
    "There's a species of jellyfish that's biologically immortal. You may not be, so get to work!",
    "If you drilled a tunnel straight through the Earth and jumped in, it would take about 42 minutes to get to the other side. Start your work journey now!",
    "There are more trees on Earth than stars in the Milky Way. Get rooted and start growing your work!",
    "The Eiffel Tower can be 15 cm taller during the summer. Expand your knowledge and get to work!",
    "The total weight of ants on Earth is estimated to be roughly equal to the total weight of humans. Even ants are busy, so should you be!",
    "Did you know you can't hum while holding your nose closed? Try it! Now get back to work.",
    "A day on Venus is longer than a year on Venus. Make your work day count!",
    "The footprints on the Moon will likely stay there for at least 100 million years. Make your mark today!",
    "In Switzerland, it is illegal to own just one guinea pig. Don't be lonely, get a work buddy! (Or just work)",
    "The average person spends about 6 months of their life waiting for red lights to turn green. Don't wait, start working!",
    "You can't fold a piece of paper in half more than 7 or 8 times. Break your limits and get to work!",
    "Did you know that peanuts are one of the ingredients of dynamite? Be explosive in your work!",
    "The state of Florida is bigger than England. Be ambitious in your work like Florida!",
    "There are 293 ways to make change for a dollar. Find your way to get working!",
    "A snail can sleep for three years. You can't. Get to work!",
    "The world's largest snowflake on record was 15 inches wide and 8 inches thick. Be unique in your work!",

    # Quotes:
    "'The only way to achieve the impossible is to believe it is possible.' - Charles Kingsleigh (Alice in Wonderland). Now go do it!",
    "'Whether you think you can, or you think you can't - you're right.' - Henry Ford. Choose to believe you can.",
    "'The expert in anything was once a beginner.' - Helen Hayes. Keep learning and growing.",
    "'Strive not to be a success, but rather to be of value.' - Albert Einstein. Make a difference today.",
    "'Do not go gentle into that good night, Old age should burn and rave at close of day; Rage, rage against the dying of the light.' - Dylan Thomas",
    "'If I have seen further it is by standing on the shoulders of Giants.' - Isaac Newton",
    "'What's money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.' - Bob Dylan",
    "'I have not failed. I've just found 10,000 ways that won't work.' - Thomas Edison",
    "'When something is important enough, you do it even if the odds are not in your favor.' - Elon Musk",
    "'If life were predictable it would cease to be life, and be without flavor.' - Eleanor Roosevelt",
    "'It is during our darkest moments that we must focus to see the light.' - Aristotle",
    "'The greatest glory in living lies not in never falling, but in rising every time we fall.' - Nelson Mandela",
    "'The way to get started is to quit talking and begin doing.' - Walt Disney",
    "'Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma – which is living with the results of other people's thinking.' - Steve Jobs",
    "'Life is what happens when you're busy making other plans.' - John Lennon",
    "'If you look at what you have in life, you'll always have more. If you look at what you don't have, you'll never have enough.' - Oprah Winfrey",
    "'The purpose of our lives is to be happy.' - Dalai Lama",
    "'Many of life's failures are people who did not realize how close they were to success when they gave up.' - Thomas A. Edison",
    "'Life is 10% what happens to me and 90% of how I react to it.' - Charles Swindoll",
    "'The big lesson in life, baby, is never be scared of anyone or anything.' - Frank Sinatra",
    "'In three words I can sum up everything I've learned about life: it goes on.' - Robert Frost",
    "'You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.' - Dr. Seuss",
    "'Life is like riding a bicycle. To keep your balance, you must keep moving.' - Albert Einstein",
    "'You only live once, but if you do it right, once is enough.' - Mae West",
    "'The journey of a thousand miles begins with a single step.' - Lao Tzu",
    "'I find that the harder I work, the more luck I seem to have.' - Thomas Jefferson",
    "'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.' - Albert Schweitzer",
    "'The only limit to our realization of tomorrow will be our doubts of today.' - Franklin D. Roosevelt",
    "'Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.' - Buddha",
    "'The greatest wealth is to live content with little.' - Plato",
]
