import enum
import unittest

from work_timer.utils.state_machine import StateMachine, handler, DisallowedStateTransitionError


class InitialStateTest(unittest.TestCase):

    def test_the_first_state_is_initial_state(self):
        class Machine(StateMachine):
            class State(enum.Enum):
                RUNNING = 1
                STOPPED = 2

        m = Machine()

        self.assertEqual(m.get_state(), Machine.State.RUNNING)

    def test_setting_initial_state_on_a_class(self):
        pass

    def test_setting_initial_state_on_instance_creation(self):
        pass


class AllowedTransitionsTest(unittest.TestCase):

    class Machine(StateMachine):
        class State(enum.Enum):
            RUNNING = 1
            STOPPED = 2
        ALLOWED_TRANSITIONS = {
            (State.RUNNING, State.STOPPED),
        }

    def test_allowed_transition(self):
        m = self.Machine()
        m.transition_to(m.State.STOPPED)
        self.assertEqual(m.get_state(), m.State.STOPPED)

    def test_disallowed_transition(self):
        m = self.Machine()
        m.transition_to(m.State.STOPPED)
        with self.assertRaises(DisallowedStateTransitionError):
            m.transition_to(m.State.RUNNING)

    def test_disallowed_transition_error_attributes(self):
        m = self.Machine()
        m.transition_to(m.State.STOPPED)
        try:
            m.transition_to(m.State.RUNNING)
        except DisallowedStateTransitionError as e:
            self.assertEqual(e.from_state, m.State.STOPPED)
            self.assertEqual(e.to_state, m.State.RUNNING)

    def test_transition_to_the_same_state_is_not_allowed(self):
        m = self.Machine()
        with self.assertRaises(DisallowedStateTransitionError):
            m.transition_to(m.State.RUNNING)


unittest.util._MAX_LENGTH = 2000


class TestAllowedTransitionsAutogeneration(unittest.TestCase):

    def test_allowed_transitions_autogenerated_from_handlers(self):

        class Machine(StateMachine):
            class State(enum.Enum):
                RUNNING = 1
                PAUSED = 2
                STOPPED = 3

            @handler(State.RUNNING, State.PAUSED)
            def on_pause(self):
                pass

            @handler(State.STOPPED)
            def on_stop(self):
                pass

        m = Machine()

        self.assertEqual(m.ALLOWED_TRANSITIONS, {
            (m.State.RUNNING, m.State.PAUSED),
            (m.State.RUNNING, m.State.STOPPED),
            (m.State.PAUSED, m.State.STOPPED),
        })


class TransitionHandlersTest(unittest.TestCase):

    def test_transition_handler_is_called_on_transition(self):

        handler_called = False

        class Machine(StateMachine):
            class State(enum.Enum):
                RUNNING = 1
                STOPPED = 2

            @handler(State.RUNNING, State.STOPPED)
            def running_to_stopped(self):
                nonlocal handler_called
                handler_called = True

        m = Machine()
        m.transition_to(m.State.STOPPED)

        self.assertTrue(handler_called)

    def test_handler_without_from_state(self):

        class Machine(StateMachine):

            def __init__(self):
                super().__init__()
                self.handler_called = False

            class State(enum.Enum):
                RUNNING = 1
                PAUSED = 2
                STOPPED = 3

            @handler(State.RUNNING, State.STOPPED)
            def running_to_stopped(self):
                self.handler_called = True

        m = Machine()
        m.transition_to(m.State.STOPPED)

        self.assertTrue(m.handler_called)


if __name__ == '__main__':
    unittest.main()
